"""Fill dashboard HTML slots and write generated data.js under outputs/."""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

from busan_imd.infographic.config import DEFAULT_INTERACTIVE_OUTPUT_DIR

ASSET_ROOT = DEFAULT_INTERACTIVE_OUTPUT_DIR
STATIC_CSS = ("layout.css", "overlays.css", "evidence.css", "policy.css")
STATIC_JS = ("overlays.js", "map.js", "policy.js", "evidence.js", "boot.js")
GENERATED_HTML_BANNER = (
    "<!-- Assembled dashboard. Edit html/, css/, and js/ in this folder. "
    "data.js is generated. -->\n"
)
GENERATED_JS_BANNER = (
    "// Generated payload. Do not edit this file; regenerate the infographic.\n"
)
PAYLOAD_NAMES = (
    "indicators",
    "assessments",
    "majorAssessments",
    "children",
    "policies",
    "labels",
    "categoryLabels",
    "accidentSummary",
    "referenceContext",
    "referenceCompositions",
    "trafficTrend",
)
_PLACEHOLDER = re.compile(r"__[A-Z0-9_]+__")


def _read_html(name: str) -> str:
    return (ASSET_ROOT / "html" / name).read_text(encoding="utf-8")


def _fill(template: str, mapping: dict[str, str]) -> str:
    result = template
    for key, value in mapping.items():
        placeholder = f"__{key}__"
        if placeholder not in result:
            raise ValueError(f"Dashboard HTML is missing placeholder {placeholder}")
        result = result.replace(placeholder, value)
    leftovers = sorted(set(_PLACEHOLDER.findall(result)))
    if leftovers:
        raise ValueError(f"Unreplaced dashboard placeholders: {leftovers}")
    return result


def _dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _render_data_js(payloads: dict[str, Any], major_category: str) -> str:
    missing = [name for name in PAYLOAD_NAMES if name not in payloads]
    if missing:
        raise ValueError(f"Dashboard data payload is missing keys: {missing}")
    assignments = "\n".join(f"const {name}={_dump(payloads[name])};" for name in PAYLOAD_NAMES)
    return (
        f"{GENERATED_JS_BANNER}{assignments}\n"
        "const detail=document.getElementById('detail');\n"
        "const policyPanel=document.getElementById('policy-panel');\n"
        f"let majorCategory={_dump(major_category)};let category=null;let selected=null;\n"
    )


def _copy_if_needed(source: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and dest.resolve() == source.resolve():
        return
    shutil.copyfile(source, dest)


def write_dashboard_files(
    output_path: Path,
    *,
    replacements: dict[str, str],
    payloads: dict[str, Any],
    major_category: str,
) -> dict[str, Path]:
    """Write generated HTML and data.js next to the editable CSS/JS in outputs/."""
    output_dir = output_path.parent
    css_dir = output_dir / "css"
    js_dir = output_dir / "js"
    written: dict[str, Path] = {"interactive_action_map": output_path}
    for name in STATIC_CSS:
        dest = css_dir / name
        _copy_if_needed(ASSET_ROOT / "css" / name, dest)
        written[f"interactive_action_map_css_{Path(name).stem}"] = dest
    for name in STATIC_JS:
        dest = js_dir / name
        _copy_if_needed(ASSET_ROOT / "js" / name, dest)
        written[f"interactive_action_map_js_{Path(name).stem}"] = dest

    data_path = js_dir / "data.js"
    data_path.parent.mkdir(parents=True, exist_ok=True)
    data_path.write_text(_render_data_js(payloads, major_category), encoding="utf-8", newline="\n")
    written["interactive_action_map_js_data"] = data_path

    parts = {
        "GUIDE": _fill(
            _read_html("guide.html"),
            {
                "INDICATOR_COUNT": replacements["INDICATOR_COUNT"],
                "CATEGORY_COUNT": replacements["CATEGORY_COUNT"],
                "MAJOR_COUNT": replacements["MAJOR_COUNT"],
            },
        ),
        "TREE": _fill(_read_html("tree.html"), {"CATEGORY_TREE": replacements["CATEGORY_TREE"]}),
        "MAP": _fill(
            _read_html("map.html"),
            {
                "HOTSPOT_COUNT": replacements["HOTSPOT_COUNT"],
                "SAFETY_RISK_COUNT": replacements["SAFETY_RISK_COUNT"],
                "AED_COUNT": replacements["AED_COUNT"],
                "PARK_COUNT": replacements["PARK_COUNT"],
                "DONG_PATHS": replacements["DONG_PATHS"],
                "HOTSPOT_MARKERS": replacements["HOTSPOT_MARKERS"],
                "SAFETY_RISK_MARKERS": replacements["SAFETY_RISK_MARKERS"],
                "AED_MARKERS": replacements["AED_MARKERS"],
                "PARK_MARKERS": replacements["PARK_MARKERS"],
            },
        ),
        "DETAIL": _read_html("detail.html"),
        "POLICY_PANEL": _read_html("policy_panel.html"),
    }
    leftover_parts = [name for name, text in parts.items() if _PLACEHOLDER.search(text)]
    if leftover_parts:
        raise ValueError(f"Unreplaced placeholders in dashboard fragments: {leftover_parts}")
    document = _fill(_read_html("document.html"), parts)
    prefix = "<!doctype html>\n"
    if document.startswith(prefix):
        document = prefix + GENERATED_HTML_BANNER + document[len(prefix) :]
    else:
        document = GENERATED_HTML_BANNER + document
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(document, encoding="utf-8", newline="\n")
    return written
